### ISSUE TITLE
Passwords should be encrypted before saved to the DB

### ISSUE THREAD

**Issue by wsingleton** [210726-java-react-serverless/bookstore#19]
Storing cleartext passwords in a deployed database is a huge security vulnerability, and puts our users at risk. Implement logic that will encrypt a new user's password before persisting them to the data source. Additionally, the login functionality will need to be updated as well.

**Comment by batainem96** [comment]
#28

**Comment by batainem96** [comment]
Some sout statements are still in there.

**Comment by batainem96** [comment]
I think this issue is resolved in the capacity that we're expecting.
