### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by wsingleton** [210726-java-react-serverless/bookstore#5]
Using `System.exit(0)` is bad practice and causes the JVM to forcibly shutdown, which can lead to many issues. A new way to gracefully shutdown the application must be implemented.

**Comment by heraldOfMechanus** [comment]
I made a pull request with my shiny new app.shutdown(); method, and even a Break to prevent runoff from telling you the input is wrong. #9

**Comment by wsingleton** [comment]
merged
